-- Starter disease & pest catalog for the seeded crops. name + symptoms are
-- localized (en/si/ta, best-effort — review by a native speaker / agronomist);
-- causes/treatment/prevention are English for now (admin can add si/ta).
-- Idempotent via INSERT OR IGNORE on stable ids. Depends on crops_lk.sql.

INSERT OR IGNORE INTO diseases
  (id, crop_id, name, kind, symptoms, causes, treatment, prevention, created_at) VALUES
  -- Paddy
  ('dis-paddy-blast','crop-paddy',
   '{"en":"Rice Blast","si":"වී බ්ලාස්ට් රෝගය","ta":"நெல் கருகல் நோய்"}','disease',
   '{"en":"Spindle-shaped grey-white lesions with brown borders on leaves; rotting at the neck of the panicle.","si":"පත්‍රවල දුඹුරු දාර සහිත අළු-සුදු තුවාල; කරලෙහි බෙල්ල කුණුවීම.","ta":"இலைகளில் பழுப்பு விளிம்புடன் சாம்பல்-வெள்ளை புள்ளிகள்; கதிரின் கழுத்து அழுகல்."}',
   '{"en":"Fungus Magnaporthe oryzae; favoured by high humidity and excess nitrogen."}',
   '{"en":"Apply tricyclazole or isoprothiolane fungicide; remove infected debris."}',
   '{"en":"Use resistant varieties, balanced nitrogen and good drainage."}',
   strftime('%s','now')),
  ('dis-paddy-bph','crop-paddy',
   '{"en":"Brown Planthopper","si":"දුඹුරු පැලෑඳුවා","ta":"பழுப்பு தத்துப்பூச்சி"}','pest',
   '{"en":"Yellowing and drying of plants in patches (hopperburn); insects clustered at the plant base.","si":"කොටස් වශයෙන් පැළ කහ පැහැ වී වියළීම; පැළ පාදයේ කෘමීන් රැස්වීම.","ta":"தாவரங்கள் பகுதி பகுதியாக மஞ்சள் நிறமாகி உலர்தல்; தாவர அடியில் பூச்சிகள்."}',
   '{"en":"Nilaparvata lugens sucking sap at the base; dense canopy and excess nitrogen."}',
   '{"en":"Drain the field for a few days; apply a recommended insecticide if the threshold is exceeded."}',
   '{"en":"Avoid excess nitrogen, keep spacing and encourage natural predators."}',
   strftime('%s','now')),
  -- Chilli
  ('dis-chilli-anthracnose','crop-chilli',
   '{"en":"Anthracnose (Fruit Rot)","si":"ඇන්ත්‍රැක්නෝස් (ගෙඩි කුණුවීම)","ta":"அந்த்ராக்னோஸ் (காய் அழுகல்)"}','disease',
   '{"en":"Sunken dark circular lesions on fruits with pinkish spore masses.","si":"ගෙඩිවල ගිලුණු අඳුරු වටකුරු තුවාල සහ රෝස පැහැ බීජාණු.","ta":"காய்களில் பள்ளமான கருமை வட்ட புள்ளிகள் மற்றும் இளஞ்சிவப்பு வித்துக்கள்."}',
   '{"en":"Colletotrichum fungi; spread by rain splash in warm humid weather."}',
   '{"en":"Spray copper or mancozeb/azoxystrobin; remove and destroy infected fruits."}',
   '{"en":"Use disease-free seed, avoid overhead irrigation and rotate crops."}',
   strftime('%s','now')),
  ('dis-chilli-thrips','crop-chilli',
   '{"en":"Thrips","si":"ත්‍රිප්ස් (පත්‍ර කරවීම)","ta":"த்ரிப்ஸ் பூச்சி"}','pest',
   '{"en":"Upward leaf curling, silvery streaks and stunted growth.","si":"පත්‍ර ඉහළට හැකිලීම, රිදී පැහැ ඉරි සහ වර්ධනය අඩුවීම.","ta":"இலைகள் மேல்நோக்கி சுருளுதல், வெள்ளி கோடுகள் மற்றும் வளர்ச்சி குன்றல்."}',
   '{"en":"Scirtothrips dorsalis feeding on tender leaves; dry weather."}',
   '{"en":"Apply spinosad or a recommended insecticide; use blue sticky traps."}',
   '{"en":"Remove weeds, avoid water stress and rotate insecticide groups."}',
   strftime('%s','now')),
  -- Tomato
  ('dis-tomato-earlyblight','crop-tomato',
   '{"en":"Early Blight","si":"මුල් අංගමාරය","ta":"முன் கருகல் நோய்"}','disease',
   '{"en":"Concentric dark rings (target spots) on older leaves with surrounding yellowing.","si":"පැරණි පත්‍රවල කේන්ද්‍රීය අඳුරු වළලු සහ වටා කහ පැහැය.","ta":"பழைய இலைகளில் வட்ட வடிவ கருமை வளையங்கள் மற்றும் சுற்றி மஞ்சள் நிறம்."}',
   '{"en":"Alternaria solani; warm wet weather and poor plant nutrition."}',
   '{"en":"Spray mancozeb or chlorothalonil; remove affected lower leaves."}',
   '{"en":"Mulch, stake plants, rotate crops and feed a balanced fertiliser."}',
   strftime('%s','now')),
  ('dis-tomato-whitefly','crop-tomato',
   '{"en":"Whitefly","si":"සුදු මැස්සා","ta":"வெள்ளை ஈ"}','pest',
   '{"en":"Tiny white insects under leaves; yellowing, sticky honeydew and sooty mould; spreads leaf curl virus.","si":"පත්‍ර යට කුඩා සුදු කෘමීන්; කහ පැහැය, ඇලෙන මී පැණි සහ දුම් පැහැ පුස්; පත්‍ර කරවීමේ වෛරසය පතුරුවයි.","ta":"இலைகளுக்கு அடியில் சிறிய வெள்ளை பூச்சிகள்; மஞ்சள் நிறம், ஒட்டும் தேன்பனி; இலைச்சுருள் வைரஸை பரப்பும்."}',
   '{"en":"Bemisia tabaci; also transmits leaf curl virus."}',
   '{"en":"Use yellow sticky traps; spray neem oil or a recommended insecticide."}',
   '{"en":"Use resistant varieties, remove weeds and protect nurseries with nets."}',
   strftime('%s','now')),
  -- Big Onion
  ('dis-bonion-purpleblotch','crop-big-onion',
   '{"en":"Purple Blotch","si":"දම් පැහැ පුල්ලි රෝගය","ta":"ஊதா புள்ளி நோய்"}','disease',
   '{"en":"Small white sunken spots that enlarge into purple lesions on leaves.","si":"පත්‍රවල කුඩා සුදු ගිලුණු පුල්ලි දම් පැහැ තුවාල බවට විශාල වීම.","ta":"இலைகளில் சிறிய வெள்ளை பள்ள புள்ளிகள் ஊதா புள்ளிகளாக பெரிதாகும்."}',
   '{"en":"Alternaria porri; high humidity and prolonged leaf wetness."}',
   '{"en":"Spray mancozeb or chlorothalonil with a sticker; remove debris."}',
   '{"en":"Use wider spacing, avoid leaf wetness and rotate crops."}',
   strftime('%s','now')),
  ('dis-bonion-thrips','crop-big-onion',
   '{"en":"Onion Thrips","si":"ලූණු ත්‍රිප්ස්","ta":"வெங்காய த்ரிப்ஸ்"}','pest',
   '{"en":"Silvery patches and white streaks on leaves; twisting and reduced bulb size.","si":"පත්‍රවල රිදී පැහැ පැල්ලම් සහ සුදු ඉරි; ඇඹරීම සහ බල්බ විශාලත්වය අඩුවීම.","ta":"இலைகளில் வெள்ளி திட்டுகள் மற்றும் வெள்ளை கோடுகள்; முறுக்கம் மற்றும் சிறிய கிழங்கு."}',
   '{"en":"Thrips tabaci feeding on leaves; hot dry weather."}',
   '{"en":"Apply spinosad or a recommended insecticide; use blue sticky traps."}',
   '{"en":"Irrigate adequately, remove crop residues and rotate crops."}',
   strftime('%s','now')),
  -- Brinjal
  ('dis-brinjal-borer','crop-brinjal',
   '{"en":"Shoot and Fruit Borer","si":"දළු හා ගෙඩි විදින පණුවා","ta":"தளிர் மற்றும் காய் துளைப்பான்"}','pest',
   '{"en":"Wilting and drooping shoots; bore holes in fruits filled with frass.","si":"දළු මැලවී එල්ලා වැටීම; ගෙඩිවල විදින සිදුරු සහ අසූචි.","ta":"தளிர்கள் வாடி தொங்குதல்; காய்களில் துளைகள் மற்றும் கழிவுகள்."}',
   '{"en":"Leucinodes orbonalis larvae tunnelling into shoots and fruits."}',
   '{"en":"Remove and destroy bored shoots and fruits; use pheromone traps; need-based insecticide."}',
   '{"en":"Use resistant varieties, remove affected parts regularly and rotate crops."}',
   strftime('%s','now')),
  ('dis-brinjal-bacwilt','crop-brinjal',
   '{"en":"Bacterial Wilt","si":"බැක්ටීරියා මැලවීම","ta":"பாக்டீரியா வாடல் நோய்"}','disease',
   '{"en":"Sudden wilting of the whole plant while leaves stay green; browning of the stem tissue.","si":"පත්‍ර කොළ පැහැව තිබියදී සම්පූර්ණ පැළය හදිසියේ මැලවීම; කඳ පටක දුඹුරු වීම.","ta":"இலைகள் பச்சையாக இருக்கும்போதே முழு தாவரமும் திடீரென வாடுதல்; தண்டு திசு பழுப்பாதல்."}',
   '{"en":"Ralstonia solanacearum in the soil; warm wet conditions."}',
   '{"en":"No effective cure; remove and destroy infected plants promptly."}',
   '{"en":"Use resistant varieties or grafting, well-drained soil and long rotations."}',
   strftime('%s','now'));
