-- Starter Knowledge Base for Sri Lankan farming. title/summary/body are localized
-- (en/si/ta, best-effort — review by an agronomist / native speaker). category is a
-- language-neutral key; crop_id is a soft link to crops_lk.sql where relevant.
-- Idempotent via INSERT OR IGNORE on stable ids.

INSERT OR IGNORE INTO articles
  (id, title, summary, body, category, crop_id, published, created_at, updated_at) VALUES
  ('kb-compost',
   '{"en":"Making Compost at Home","si":"ගෙදරදී කොම්පෝස්ට් සෑදීම","ta":"வீட்டில் உரம் தயாரித்தல்"}',
   '{"en":"Turn kitchen and garden waste into rich organic fertiliser.","si":"කුස්සියේ හා ගෙවතු අපද්‍රව්‍ය පොහොසත් කාබනික පොහොරක් කරගන්න.","ta":"சமையலறை மற்றும் தோட்டக் கழிவுகளை வளமான கரிம உரமாக மாற்றுங்கள்."}',
   '{"en":"Layer green waste (vegetable scraps, fresh leaves) with brown waste (dry leaves, straw) in a shaded pit or bin. Keep it as moist as a wrung sponge and turn it every week or two for air. In about 8-12 weeks it becomes dark, crumbly compost you can mix into beds before planting.","si":"සෙවණ සහිත වළක හෝ බඳුනක කොළ පැහැ අපද්‍රව්‍ය (එළවළු කැබලි, අළුත් කොළ) දුඹුරු අපද්‍රව්‍ය (වියළි කොළ, පිදුරු) සමඟ තට්ටු වශයෙන් දමන්න. මිරිකූ ස්පොන්ජියක් මෙන් තෙතමනය පවත්වා, වාතය සඳහා සතියකට වරක් දෙකකට වරක් පෙරළන්න. සති 8-12කින් එය වගාවට පෙර පාත්තිවලට මිශ්‍ර කළ හැකි අඳුරු, කුඩු පොහොර බවට පත් වේ.","ta":"நிழலான குழியில் அல்லது தொட்டியில் பச்சைக் கழிவுகளை (காய்கறித் துண்டுகள், பசுமையான இலைகள்) பழுப்புக் கழிவுகளுடன் (உலர்ந்த இலைகள், வைக்கோல்) அடுக்கடுக்காக இடுங்கள். பிழிந்த கடற்பஞ்சு போல ஈரப்பதத்தை வைத்து, காற்றுக்காக வாரம் ஒருமுறை புரட்டுங்கள். சுமார் 8-12 வாரங்களில் அது நடவுக்கு முன் பாத்திகளில் கலக்கக்கூடிய கருமையான உரமாக மாறும்."}',
   'soil', NULL, 1, strftime('%s','now'), strftime('%s','now')),

  ('kb-drip-irrigation',
   '{"en":"Drip Irrigation Basics","si":"බින්දු ජලസේචනය මූලික කරුණු","ta":"சொட்டு நீர்ப்பாசன அடிப்படைகள்"}',
   '{"en":"Save water and feed roots directly with simple drip lines.","si":"සරල බින්දු රේඛා මගින් ජලය ඉතිරි කර මුල්වලට කෙලින්ම සපයන්න.","ta":"எளிய சொட்டு குழாய்கள் மூலம் நீரைச் சேமித்து வேர்களுக்கு நேரடியாக வழங்குங்கள்."}',
   '{"en":"Drip irrigation delivers water slowly to the base of each plant, cutting waste and keeping leaves dry (which reduces disease). Lay the main line along the bed and place emitters near each plant. Run it in the early morning, and check emitters weekly for clogging. It suits vegetables and is ideal where water is scarce.","si":"බින්දු ජලසේචනය එක් එක් පැළයේ පාදයට සෙමින් ජලය සපයයි, නාස්තිය අඩු කර පත්‍ර වියළිව තබයි (එය රෝග අඩු කරයි). ප්‍රධාන රේඛාව පාත්තිය දිගේ දමා එක් එක් පැළය අසල විමෝචක තබන්න. උදෑසන එය ක්‍රියාත්මක කර, සතිපතා විමෝචක අවහිර වීම පරීක්ෂා කරන්න. එය එළවළුවලට සුදුසු අතර ජලය හිඟ තැන්වලට වඩාත් සුදුසුය.","ta":"சொட்டு நீர்ப்பாசனம் ஒவ்வொரு செடியின் அடிப்பகுதிக்கும் மெதுவாக நீரை வழங்கி, விரயத்தைக் குறைத்து இலைகளை உலர்வாக வைக்கிறது (இது நோயைக் குறைக்கிறது). முக்கிய குழாயை பாத்தி நெடுகிலும் அமைத்து ஒவ்வொரு செடிக்கும் அருகில் சொட்டிகளை வைக்கவும். அதிகாலையில் இயக்கி, வாரந்தோறும் அடைப்பை சரிபார்க்கவும். இது காய்கறிகளுக்கு ஏற்றது, நீர் பற்றாக்குறை உள்ள இடங்களுக்கு சிறந்தது."}',
   'irrigation', NULL, 1, strftime('%s','now'), strftime('%s','now')),

  ('kb-maha-yala',
   '{"en":"Planning the Maha and Yala Seasons","si":"මහ හා යල කන්න සැලසුම් කිරීම","ta":"மஹா மற்றும் யால பருவங்களைத் திட்டமிடல்"}',
   '{"en":"Match your crop to Sri Lanka two monsoon-driven growing seasons.","si":"ඔබේ බෝගය ශ්‍රී ලංකාවේ මෝසම් කන්න දෙකට ගලපන්න.","ta":"உங்கள் பயிரை இலங்கையின் இரு பருவமழை சாகுபடி பருவங்களுடன் பொருத்துங்கள்."}',
   '{"en":"Sri Lanka has two main seasons. Maha (roughly September to March) is the main season fed by the north-east monsoon, with more reliable rain. Yala (around April/May to August) is shorter and drier, suited to crops that need less water or to areas with irrigation. Choose varieties and planting dates that fit the season, and plan irrigation for Yala where rainfall is low.","si":"ශ්‍රී ලංකාවේ ප්‍රධාන කන්න දෙකක් ඇත. මහ (ආසන්න වශයෙන් සැප්තැම්බර් සිට මාර්තු) යනු ඊසානදිග මෝසමින් පෝෂණය වන, වඩාත් විශ්වසනීය වර්ෂාවක් සහිත ප්‍රධාන කන්නයයි. යල (අප්‍රේල්/මැයි සිට අගෝස්තු දක්වා) කෙටි හා වියළි අතර අඩු ජලය අවශ්‍ය බෝග හෝ ජලසම්පාදනය ඇති ප්‍රදේශවලට සුදුසුය. කන්නයට ගැලපෙන ප්‍රභේද හා වැපිරීමේ දින තෝරා, වර්ෂාව අඩු යල සඳහා ජලසම්පාදනය සැලසුම් කරන්න.","ta":"இலங்கையில் இரு முக்கிய பருவங்கள் உள்ளன. மஹா (சுமார் செப்டம்பர் முதல் மார்ச் வரை) வடகிழக்குப் பருவமழையால் ஊட்டப்படும் முக்கிய பருவம், நம்பகமான மழையுடன். யால (ஏப்ரல்/மே முதல் ஆகஸ்ட் வரை) குறுகியதும் வறண்டதும், குறைந்த நீர் தேவைப்படும் பயிர்களுக்கு அல்லது நீர்ப்பாசன பகுதிகளுக்கு ஏற்றது. பருவத்திற்கு ஏற்ற ரகங்களையும் நடவு தேதிகளையும் தேர்ந்தெடுத்து, மழை குறைவான யாலவுக்கு நீர்ப்பாசனத்தைத் திட்டமிடுங்கள்."}',
   'seasonal', NULL, 1, strftime('%s','now'), strftime('%s','now')),

  ('kb-ipm',
   '{"en":"Integrated Pest Management","si":"ඒකාබද්ධ පළිබෝධ කළමනාකරණය","ta":"ஒருங்கிணைந்த பூச்சி மேலாண்மை"}',
   '{"en":"Control pests with less chemical spray by combining methods.","si":"ක්‍රම කිහිපයක් එක්කර අඩු රසායනික ඉසීමෙන් පළිබෝධ පාලනය කරන්න.","ta":"முறைகளை இணைத்து குறைந்த இரசாயனத் தெளிப்புடன் பூச்சிகளைக் கட்டுப்படுத்துங்கள்."}',
   '{"en":"Integrated Pest Management (IPM) uses several tools together instead of relying on one spray. Scout fields regularly, encourage natural predators, use traps (yellow or blue sticky cards), rotate crops, and keep plants healthy. Use pesticides only when pests cross a threshold, and rotate the chemical groups so pests do not build resistance.","si":"ඒකාබද්ධ පළිබෝධ කළමනාකරණය (IPM) එක් ඉසීමක් මත රඳා නොසිට මෙවලම් කිහිපයක් එකට භාවිතා කරයි. කෙත් නිතිපතා නිරීක්ෂණය කරන්න, ස්වභාවික විලෝපිකයන් දිරිගන්වන්න, උගුල් (කහ හෝ නිල් ඇලෙන කාඩ්) භාවිතා කරන්න, බෝග මාරු කරන්න, පැළ නිරෝගීව තබන්න. පළිබෝධ සීමාවක් ඉක්මවූ විට පමණක් පළිබෝධනාශක භාවිතා කර, ප්‍රතිරෝධය ගොඩනොනැගෙන ලෙස රසායනික කාණ්ඩ මාරු කරන්න.","ta":"ஒருங்கிணைந்த பூச்சி மேலாண்மை (IPM) ஒரே தெளிப்பை நம்பாமல் பல கருவிகளை ஒன்றாகப் பயன்படுத்துகிறது. வயல்களை தவறாமல் கண்காணியுங்கள், இயற்கை வேட்டையாடிகளை ஊக்குவியுங்கள், பொறிகளை (மஞ்சள் அல்லது நீல ஒட்டும் அட்டைகள்) பயன்படுத்துங்கள், பயிர் சுழற்சி செய்யுங்கள், செடிகளை ஆரோக்கியமாக வைத்திருங்கள். பூச்சிகள் வரம்பை மீறும்போது மட்டுமே பூச்சிக்கொல்லியைப் பயன்படுத்தி, எதிர்ப்புத்திறன் உருவாகாமல் இரசாயனக் குழுக்களை மாற்றுங்கள்."}',
   'pest', NULL, 1, strftime('%s','now'), strftime('%s','now')),

  ('kb-paddy-water',
   '{"en":"Water Management in Paddy","si":"වී වගාවේ ජල කළමනාකරණය","ta":"நெல் சாகுபடியில் நீர் மேலாண்மை"}',
   '{"en":"Use water wisely across the paddy growth stages.","si":"වී වර්ධන අවධීන් පුරා ජලය බුද්ධිමත්ව භාවිතා කරන්න.","ta":"நெல் வளர்ச்சி நிலைகளில் நீரை அறிவுடன் பயன்படுத்துங்கள்."}',
   '{"en":"Paddy does not need deep standing water at all times. Keep shallow water (2-5 cm) during tillering, and let the field dry briefly between irrigations (alternate wetting and drying) to save water and strengthen roots. Maintain water during flowering, then drain about 10 days before harvest so the crop matures evenly.","si":"වී වගාවට සැම විටම ගැඹුරු ජලය අවශ්‍ය නැත. අතු හටගැනීමේදී නොගැඹුරු ජලය (සෙ.මී. 2-5) තබා, ජලසම්පාදන අතර කෙත් කෙටියෙන් වියළීමට ඉඩ දෙන්න (විකල්ප තෙත් කිරීම හා වියළීම) — එයින් ජලය ඉතිරි වී මුල් ශක්තිමත් වේ. මල් හටගැනීමේදී ජලය පවත්වා, පසුව අස්වැන්නට දින 10කට පමණ පෙර ජලය බැස යවන්න.","ta":"நெல்லுக்கு எப்போதும் ஆழமான தேங்கிய நீர் தேவையில்லை. கிளைத்தல் நிலையில் ஆழமற்ற நீரை (2-5 செ.மீ) வைத்து, நீர்ப்பாசனங்களுக்கு இடையே வயல் சிறிது உலர அனுமதியுங்கள் (மாறி மாறி நனைத்தல் மற்றும் உலர்த்தல்) — இது நீரைச் சேமித்து வேர்களை வலுப்படுத்தும். பூக்கும் நிலையில் நீரைப் பராமரித்து, அறுவடைக்கு சுமார் 10 நாட்களுக்கு முன் நீரை வடியவிடுங்கள்."}',
   'crop-guide', 'crop-paddy', 1, strftime('%s','now'), strftime('%s','now'));
